name: another_iptv_player
description: "Another IPTV Player"
publish_to: "none"

version: 0.8.1+10

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  get_it: ^7.2.0
  media_kit:
    git:
      url: https://github.com/media-kit/media-kit.git
      path: media_kit
      ref: main
  media_kit_video:
    git:
      url: https://github.com/media-kit/media-kit.git
      path: media_kit_video
      ref: main
  media_kit_libs_video:
    git:
      url: https://github.com/media-kit/media-kit.git
      path: libs/universal/media_kit_libs_video
      ref: main
  provider: ^6.1.1
  drift: ^2.26.1
  sqlite3_flutter_libs: ^0.5.34
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  cached_network_image: ^3.4.1
  audio_service: ^0.18.18
  just_audio: ^0.10.4
  rxdart: ^0.28.0
  flutter_in_app_pip: ^1.7.4
  flutter_launcher_icons: ^0.14.4
  persistent_bottom_nav_bar: ^6.2.1
  shared_preferences: ^2.5.3
  audio_session: ^0.2.2
  drift_dev: any
  sqlite3: any
  path_provider: any
  path: any
  meta: any
  file_picker: ^10.2.0
  uuid: ^4.5.1
  collection: ^1.19.1
  connectivity_plus: ^6.1.4

dependency_overrides:
  media_kit:
    git:
      url: https://github.com/media-kit/media-kit.git
      path: media_kit
      ref: main

  media_kit_video:
    git:
      url: https://github.com/media-kit/media-kit.git
      path: media_kit_video
      ref: main

  media_kit_libs_video:
    git:
      url: https://github.com/media-kit/media-kit.git
      path: libs/universal/media_kit_libs_video
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.4
  flutter_lints: ^5.0.0
  build_web_compilers: ^4.1.5

  build: any
  mockito: ^5.4.6
flutter:
  uses-material-design: true
  generate: true

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  image_path: "assets/logo.png"
  min_sdk_android: 21
  macos:
    generate: true
    image_path: "assets/logo.png"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48
  linux:
    generate: true
    image_path: "assets/logo.png"

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
